### ISSUE TITLE
Adding any JS code to return results in react error

### ISSUE THREAD

**Issue by Muchaszewski** [ReactUnity/core#49]
When adding any JS code to the return method in the functional component we get an error that breaks react UI.

```
export default function MyFComponent() {
    return<>
        {console.log("noo... I crashed UI :( ")}
    </>
}
```
**Expected result**
Console log is written with the message

**Logs**
```
The above error occurred in the <MyFComponent> component:

    at MyFComponent(webpack-internal:///./src/pages/MyFComponent.tsx:45:66)
    at Outlet (webpack-internal:///./node_modules/react-router/index.js:903:26)
    at main
    at Layout (webpack-internal:///./src/pages/Layout.tsx:16:81)
    at Routes (webpack-internal:///./node_modules/react-router/index.js:1002:24)
    at Router (webpack-internal:///./node_modules/react-router/index.js:927:30)
    at MemoryRouter (webpack-internal:///./node_modules/react-router/index.js:833:23)
    at App
    at GlobalsProvider (webpack-internal:///./node_modules/@reactunity/renderer/dist/src/helpers/dictionary-watcher.js:37:23)
    at ErrorBoundary (webpack-internal:///./node_modules/@reactunity/renderer/dist/src/views/error-boundary.js:60:24)
    at DefaultView (webpack-internal:///./node_modules/@reactunity/renderer/dist/src/views/default-view.js:12:21)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
UnityEngine.Debug:LogError (object)
ReactUnity.Scripting.DomProxies.ConsoleProxy:GenericLog (object,System.Action`1<string>,object[]) (at Packages/react-unity-core/Runtime/Scripting/DomProxies/Console.cs:40)
ReactUnity.Scripting.DomProxies.ConsoleProxy:error (object) (at Packages/react-unity-core/Runtime/Scripting/DomProxies/Console.cs:81)
System.Reflection.MethodBase:Invoke (object,object[])
Microsoft.ClearScript.Util.InvokeHelpers:InvokeMethod (Microsoft.ClearScript.Util.IHostInvokeContext,object,System.Reflection.MethodInfo,object[])
Microsoft.ClearScript.HostItem/MethodBindSuccess:Invoke (Microsoft.ClearScript.HostItem)
Microsoft.ClearScript.HostItem:InvokeMethod (string,System.Type[],object[],object[])
Microsoft.ClearScript.HostItem:InvokeMethod (string,object[],object[])
Microsoft.ClearScript.HostItem:InvokeHostMember (string,System.Reflection.BindingFlags,object[],object[],System.Globalization.CultureInfo,bool&)
Microsoft.ClearScript.HostItem:InvokeMember (string,System.Reflection.BindingFlags,object[],object[],System.Globalization.CultureInfo,bool,bool&)
Microsoft.ClearScript.HostItem:InvokeMember (string,System.Reflection.BindingFlags,object[],object[],System.Globalization.CultureInfo,bool)
Microsoft.ClearScript.HostMethod:TryInvoke (Microsoft.ClearScript.Util.IHostInvokeContext,System.Reflection.BindingFlags,object[],object[],object&)
Microsoft.ClearScript.Util.InvokeHelpers:TryInvokeObject (Microsoft.ClearScript.Util.IHostInvokeContext,object,System.Reflection.BindingFlags,object[],object[],bool,object&)
Microsoft.ClearScript.HostItem:InvokeHostMember (string,System.Reflection.BindingFlags,object[],object[],System.Globalization.CultureInfo,bool&)
Microsoft.ClearScript.HostItem:InvokeMember (string,System.Reflection.BindingFlags,object[],object[],System.Globalization.CultureInfo,bool,bool&)
Microsoft.ClearScript.HostItem/<>c__DisplayClass141_0:<InvokeReflectMember>b__0 ()
Microsoft.ClearScript.ScriptEngine:HostInvoke<object> (System.Func`1<object>)
Microsoft.ClearScript.HostItem:HostInvoke<object> (System.Func`1<object>)
Microsoft.ClearScript.HostItem:InvokeReflectMember (string,System.Reflection.BindingFlags,object[],System.Globalization.CultureInfo,string[],bool&)
Microsoft.ClearScript.HostItem:InvokeReflectMember (string,System.Reflection.BindingFlags,object[],System.Globalization.CultureInfo,string[])
Microsoft.ClearScript.HostItem:System.Reflection.IReflect.InvokeMember (string,System.Reflection.BindingFlags,System.Reflection.Binder,object,object[],System.Reflection.ParameterModifier[],System.Globalization.CultureInfo,string[])
Microsoft.ClearScript.HostItem:Microsoft.ClearScript.Util.IDynamic.Invoke (bool,object[])
Microsoft.ClearScript.V8.V8ProxyHelpers:InvokeHostObject (object,bool,object[])
Microsoft.ClearScript.V8.V8ProxyHelpers:InvokeHostObject (intptr,bool,object[])
Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyManaged:InvokeHostObject (intptr,bool,Microsoft.ClearScript.V8.SplitProxy.StdV8ValueArray/Ptr,Microsoft.ClearScript.V8.SplitProxy.V8Value/Ptr)
Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative/Impl_Windows_X64:Microsoft.ClearScript.V8.SplitProxy.IV8SplitProxyNative.V8Object_Invoke (Microsoft.ClearScript.V8.SplitProxy.V8Object/Handle,bool,object[])
Microsoft.ClearScript.V8.SplitProxy.V8ObjectImpl/<>c__DisplayClass18_0:<Invoke>b__0 (Microsoft.ClearScript.V8.SplitProxy.IV8SplitProxyNative)
Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative:Invoke<object> (System.Func`2<Microsoft.ClearScript.V8.SplitProxy.IV8SplitProxyNative, object>)
Microsoft.ClearScript.V8.SplitProxy.V8ObjectImpl:Invoke (bool,object[])
Microsoft.ClearScript.V8.V8ScriptItem/<>c__DisplayClass21_0:<Invoke>b__0 ()
Microsoft.ClearScript.ScriptEngine:ScriptInvokeInternal<object> (System.Func`1<object>)
Microsoft.ClearScript.V8.V8ScriptEngine/<>c__DisplayClass120_0`1<object>:<ScriptInvoke>b__0 ()
Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyManaged:InvokeHostAction (intptr)
Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative/Impl_Windows_X64:Microsoft.ClearScript.V8.SplitProxy.IV8SplitProxyNative.V8Context_InvokeWithLock (Microsoft.ClearScript.V8.SplitProxy.V8Context/Handle,intptr)
Microsoft.ClearScript.V8.SplitProxy.V8ContextProxyImpl/<>c__DisplayClass13_0:<InvokeWithLock>b__0 (Microsoft.ClearScript.V8.SplitProxy.IV8SplitProxyNative)
Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative:Invoke (System.Action`1<Microsoft.ClearScript.V8.SplitProxy.IV8SplitProxyNative>)
Microsoft.ClearScript.V8.SplitProxy.V8ContextProxyImpl:InvokeWithLock (System.Action)
Microsoft.ClearScript.V8.V8ScriptEngine:ScriptInvoke<object> (System.Func`1<object>)
Microsoft.ClearScript.V8.V8ScriptItem:Invoke (bool,object[])
ReactUnity.Helpers.Callback:Call (object[]) (at Packages/react-unity-core/Runtime/Helpers/Callback.cs:111)
ReactUnity.Helpers.Callback:Call () (at Packages/react-unity-core/Runtime/Helpers/Callback.cs:72)
ReactUnity.Scheduling.DefaultScheduler/<>c__DisplayClass3_0:<setTimeout>b__0 () (at Packages/react-unity-core/Runtime/Scheduling/DefaultScheduler.cs:19)
ReactUnity.Scheduling.RuntimeDispatcher/<TimeoutCoroutine>d__30:MoveNext () (at Packages/react-unity-core/Runtime/Scheduling/RuntimeDispatcher.cs:211)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

```

**Comment by KurtGokhan** [comment]
Released in v0.10.0
